"""feat: ai config table schema

Revision ID: d405327c6fcd
Revises: 
Create Date: 2026-04-27 10:51:00.186875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd405327c6fcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('nickname', sa.String(length=128), nullable=True, comment='昵称'),
    sa.Column('phone', sa.String(length=64), nullable=True, comment='手机号'),
    sa.Column('mail', sa.String(length=256), nullable=True, comment='邮箱'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='用户编号'),
    sa.Column('seat', sa.String(length=64), nullable=True, comment='座位编号'),
    sa.Column('department', sa.String(length=64), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=64), nullable=True, comment='职位'),
    sa.Column('superior', sa.String(length=64), nullable=True, comment='上级'),
    sa.Column('login_type', sa.String(length=64), nullable=True, comment='登录类型:single;many'),
    sa.Column('is_tourist', sa.Integer(), nullable=False, comment='0-游客账户;1-非游客账户'),
    sa.Column('creator', sa.String(length=32), nullable=True, comment='创建人'),
    sa.Column('creator_id', sa.BigInteger(), nullable=True, comment='创建人id'),
    sa.Column('modifier', sa.String(length=32), nullable=True, comment='更新人'),
    sa.Column('modifier_id', sa.BigInteger(), nullable=True, comment='更新人id'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_agent_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('agent_id', sa.String(length=64), nullable=False, comment='Agent ID'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('default_model_key', sa.String(length=64), nullable=True, comment='默认模型 key'),
    sa.Column('allowed_model_keys_json', sa.JSON(), nullable=False, comment='允许使用的模型 key'),
    sa.Column('default_skill_ids_json', sa.JSON(), nullable=False, comment='默认 skill ID'),
    sa.Column('default_mcp_server_ids_json', sa.JSON(), nullable=False, comment='默认 MCP server'),
    sa.Column('allow_request_model_override', sa.Boolean(), nullable=False, comment='是否允许请求覆盖模型'),
    sa.Column('allow_request_mcp_override', sa.Boolean(), nullable=False, comment='是否允许请求覆盖 MCP'),
    sa.Column('supports_stream', sa.Boolean(), nullable=False, comment='是否支持流式'),
    sa.Column('approval_policy_key', sa.String(length=64), nullable=True, comment='审批策略 key'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展元数据'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_config_agent_id'), 'ai_agent_config', ['agent_id'], unique=True)
    op.create_table('ai_agent_mcp_binding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('agent_id', sa.String(length=64), nullable=False, comment='Agent ID'),
    sa.Column('server_key', sa.String(length=64), nullable=False, comment='MCP server 稳定标识'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用绑定'),
    sa.Column('required_approval', sa.Boolean(), nullable=False, comment='是否强制审批'),
    sa.Column('allow_auto_route', sa.Boolean(), nullable=False, comment='是否允许自动路由'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_mcp_binding_agent_id'), 'ai_agent_mcp_binding', ['agent_id'], unique=False)
    op.create_index('ix_ai_agent_mcp_binding_agent_server', 'ai_agent_mcp_binding', ['agent_id', 'server_key'], unique=True)
    op.create_index(op.f('ix_ai_agent_mcp_binding_server_key'), 'ai_agent_mcp_binding', ['server_key'], unique=False)
    op.create_table('ai_mcp_server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('server_key', sa.String(length=64), nullable=False, comment='MCP server 稳定标识'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='MCP server 名称'),
    sa.Column('transport', sa.String(length=32), nullable=False, comment='传输方式'),
    sa.Column('command', sa.String(length=256), nullable=True, comment='stdio 启动命令'),
    sa.Column('args_json', sa.JSON(), nullable=False, comment='stdio 命令参数'),
    sa.Column('url', sa.String(length=1024), nullable=True, comment='远程 MCP 地址'),
    sa.Column('headers_encrypted_json', sa.JSON(), nullable=False, comment='加密后的请求头'),
    sa.Column('env_encrypted_json', sa.JSON(), nullable=False, comment='加密后的环境变量'),
    sa.Column('cwd', sa.String(length=512), nullable=True, comment='stdio 工作目录'),
    sa.Column('tool_prefix', sa.String(length=64), nullable=True, comment='工具名前缀'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('auto_route_enabled', sa.Boolean(), nullable=False, comment='是否允许自动路由'),
    sa.Column('route_keywords_json', sa.JSON(), nullable=False, comment='自动路由关键词'),
    sa.Column('timeout_seconds', sa.Float(), nullable=True, comment='初始化超时'),
    sa.Column('read_timeout_seconds', sa.Float(), nullable=True, comment='读取超时'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
    sa.Column('include_instructions', sa.Boolean(), nullable=False, comment='是否注入 MCP instructions'),
    sa.Column('risk_level', sa.String(length=16), nullable=False, comment='风险等级'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展元数据'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_mcp_server_server_key'), 'ai_mcp_server', ['server_key'], unique=True)
    op.create_table('ai_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('model_key', sa.String(length=64), nullable=False, comment='模型内部稳定标识'),
    sa.Column('provider_key', sa.String(length=64), nullable=False, comment='供应商稳定标识'),
    sa.Column('model_name', sa.String(length=128), nullable=False, comment='供应商侧模型名'),
    sa.Column('display_name', sa.String(length=128), nullable=True, comment='展示名称'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('context_window', sa.Integer(), nullable=True, comment='上下文窗口'),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True, comment='最大输出 token'),
    sa.Column('supports_stream', sa.Boolean(), nullable=False, comment='是否支持流式'),
    sa.Column('supports_tools', sa.Boolean(), nullable=False, comment='是否支持工具调用'),
    sa.Column('supports_json_output', sa.Boolean(), nullable=False, comment='是否支持 JSON 输出'),
    sa.Column('input_price_per_1k', sa.Float(), nullable=True, comment='输入 token 单价/1k'),
    sa.Column('output_price_per_1k', sa.Float(), nullable=True, comment='输出 token 单价/1k'),
    sa.Column('risk_level', sa.String(length=16), nullable=False, comment='风险等级'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展元数据'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_model_key'), 'ai_model', ['model_key'], unique=True)
    op.create_index(op.f('ix_ai_model_provider_key'), 'ai_model', ['provider_key'], unique=False)
    op.create_table('ai_model_provider',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('provider_key', sa.String(length=64), nullable=False, comment='供应商稳定标识'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='供应商名称'),
    sa.Column('provider_type', sa.String(length=64), nullable=False, comment='供应商类型'),
    sa.Column('base_url', sa.String(length=512), nullable=True, comment='供应商 API 地址'),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True, comment='加密后的 API Key'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('timeout_seconds', sa.Float(), nullable=True, comment='请求超时时间'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='最大重试次数'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='扩展元数据'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_provider_provider_key'), 'ai_model_provider', ['provider_key'], unique=True)
    op.create_table('aps_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务id'),
    sa.Column('trigger_type', sa.String(length=16), nullable=False, comment='触发器类型:date;interval;cron'),
    sa.Column('trigger_param', sa.JSON(), nullable=False, comment='触发器参数'),
    sa.Column('task_function_name', sa.String(length=255), nullable=True, comment='任务函数名称'),
    sa.Column('task_function_args', sa.JSON(), nullable=False, comment='任务参数:args'),
    sa.Column('task_function_kwargs', sa.JSON(), nullable=False, comment='任务参数:kwargs'),
    sa.Column('create_time', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('create_timestamp', sa.BigInteger(), nullable=False, comment='创建时间戳'),
    sa.Column('update_timestamp', sa.BigInteger(), nullable=False, comment='更新时间戳'),
    sa.Column('is_deleted', sa.BigInteger(), nullable=True, comment='逻辑删除标识'),
    sa.Column('status', sa.BigInteger(), nullable=True, comment='状态(通用字段)'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aps_tasks')
    op.drop_index(op.f('ix_ai_model_provider_provider_key'), table_name='ai_model_provider')
    op.drop_table('ai_model_provider')
    op.drop_index(op.f('ix_ai_model_provider_key'), table_name='ai_model')
    op.drop_index(op.f('ix_ai_model_model_key'), table_name='ai_model')
    op.drop_table('ai_model')
    op.drop_index(op.f('ix_ai_mcp_server_server_key'), table_name='ai_mcp_server')
    op.drop_table('ai_mcp_server')
    op.drop_index(op.f('ix_ai_agent_mcp_binding_server_key'), table_name='ai_agent_mcp_binding')
    op.drop_index('ix_ai_agent_mcp_binding_agent_server', table_name='ai_agent_mcp_binding')
    op.drop_index(op.f('ix_ai_agent_mcp_binding_agent_id'), table_name='ai_agent_mcp_binding')
    op.drop_table('ai_agent_mcp_binding')
    op.drop_index(op.f('ix_ai_agent_config_agent_id'), table_name='ai_agent_config')
    op.drop_table('ai_agent_config')
    op.drop_table('admin')
    # ### end Alembic commands ###
